global: CODECOV_TOKEN="2215f466-5f0d-417f-b4f3-ea60ccdb863e"

language: java
jdk:
- oraclejdk8
sudo: false
script: mvn clean verify
script: "mvn cobertura:cobertura"
after_success:
- bash <(curl -s https://codecov.io/bash) -t "2215f466-5f0d-417f-b4f3-ea60ccdb863e"
